import "./globals.css";
import MainNav from "@/Components/Header/MainNav";
import Footer from "@/Components/Footer/Footer";
import PageTransition from "@/Components/layout/PageTransition";
import PromoBanner from "@/Components/Header/PromoBanner";

export const metadata = {
  title: "Gifters",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Promotional Banner - At the very top */}
        <PromoBanner />

        <div className="flex flex-col min-h-screen pt-10 sm:pt-12">
          <MainNav />

          <PageTransition>
            <main className="pt-15 ">{children}</main>
          </PageTransition>

          <Footer />
        </div>
      </body>
    </html>
  );
}
